#!/bin/bash

### 0. Adapt to your needs ###
export nnUNet_raw=/omics/groups/OE0441/E132-Projekte/Projects/2024_MICCAI24_ToothFairy2/nnUNet_raw
CODE_PATH=/home/isensee/git_repos/radbouduni_2023_cbctteethsegmentation
SEMSEG_DATASET_NAME='Dataset121_ToothFairy2_Teeth'
INSTSEG_DATASET_NAME='Dataset123_ToothFairy2fixed_teeth_spacing02_brd3px'
REF_FOLDER_RESAMPLING=${nnUNet_raw}/Dataset119_ToothFairy2_All/imagesTr

# We don't need to run test set inference we can just use the predictions generated by nnU-Net in the final validation
# --> skip: 1. Resize Instance Data
# --> skip: 2.1 semantic segmentation branch
# --> skip: 2.2 instances segmentation branch

INSTSEG_TRAINER=nnUNetTrainer
SEMSEG_TRAINER=nnUNetTrainer_onlyMirror01_DASegOrd0
INSTSEG_CONFIG=3d_fullres_resample_torch_192_bs8_ctnorm
SEMSEG_CONFIG=3d_fullres_resample_torch_256_bs8_ctnorm
NNUNET_TRAINING_INSTSEG=${INSTSEG_TRAINER}__nnUNetPlans__${INSTSEG_CONFIG}
NNUNET_TRAINING_SEMSEG=${SEMSEG_TRAINER}__nnUNetPlans__${SEMSEG_CONFIG}

# 3. Convert border-core to instances
python ${CODE_PATH}/toothseg/toothseg/postprocess_predictions/border_core_to_instances.py \
-i ${nnUNet_results}/${INSTSEG_DATASET_NAME}/${NNUNET_TRAINING_INSTSEG}/fold_5/validation \
-o ${nnUNet_results}/${INSTSEG_DATASET_NAME}/${NNUNET_TRAINING_INSTSEG}/fold_5/validation_instances \
-np 64
# 4. Resize instances to original image spacing
python ${CODE_PATH}/toothseg/toothseg/postprocess_predictions/resize_predictions.py \
-i ${nnUNet_results}/${INSTSEG_DATASET_NAME}/${NNUNET_TRAINING_INSTSEG}/fold_5/validation_instances \
-o ${nnUNet_results}/${INSTSEG_DATASET_NAME}/${NNUNET_TRAINING_INSTSEG}/fold_5/validation_instances_resized \
-ref ${REF_FOLDER_RESAMPLING} -np 64

# 5. Assign tooth labels
python ${CODE_PATH}/toothseg/toothseg/postprocess_predictions/assign_majority_tooth_labels.py \
-ifolder ${nnUNet_results}/${INSTSEG_DATASET_NAME}/${NNUNET_TRAINING_INSTSEG}/fold_5/validation_instances_resized \
-sfolder ${nnUNet_results}/${SEMSEG_DATASET_NAME}/${NNUNET_TRAINING_SEMSEG}/fold_5/validation \
-o ${nnUNet_results}/${INSTSEG_DATASET_NAME}/${NNUNET_TRAINING_INSTSEG}/fold_5/validation_final_predictions_merged \
-np 64