work_dir: '/home/mkaailab/Documents/logs/relunet'
version: 4
seed: 0

datamodule:
  root: '/mnt/diag/CBCT/tooth_segmentation/data'
  # root: '/mnt/diag/CBCT/tooth_segmentation/commercial/Test_Data'
  # scan_dir: 'Dataset164_Filtered_Classes/imagesTs'
  scan_dir: 'ToothFairy2_Dataset_Lars/Split_Dataset/ToothFairy2_Teeth_Dataset/imagesTr'
  scan_dir: 'ToothFairy2_Dataset_Lars/Split_Dataset/ToothFairy2_Teeth_Dataset/imagesTs'
  # scan_dir: 'cbcts'
  # seg_dir: 'Dataset164_All_Classes/labelsTr'
  seg_dir: 'ToothFairy2_Dataset_Lars/Split_Dataset/ToothFairy2_Jaws_Dataset/labelsTr'
  instances_dir: ''
  cache_dir: '/home/mkaailab/Documents/CBCT/baselines/data'
  regular_spacing: null
  norm_clip: [0, 4095]
  norm_method: 'symmetric'
  crop_size: [128, 96, 128]
  patch_size: [96, 128, 128]
  regex_filter: 'janna-silent'  # large FOV
  regex_filter: 'agnesse-brainy-wildcat'  # empty segmentation
  regex_filter: 'beatrisa'  # only small root remnants
  regex_filter: ''
  exclude: []
  val_size: 0.1
  include_val_as_train: True
  test_size: 0.0
  batch_size: 2
  num_workers: 12
  persistent_workers: False
  pin_memory: False
  pre_transform: []
  aug_transform: ['RandomXAxisFlip']
  transform: []
  roi:
    pre_transform: ['Downsample']
  multiclass:
    regular_spacing: 0.7
    pre_transform: ['VOICrop']
    transform: ['FDIAsClass']
  single_tooth:
    regular_spacing: 0.25
    instances_dir: 'multiclassPr'
    pre_transform: ['MatchPredToGTInstances', 'ToothPatches']
    transform: ['RandomPatches']
    max_patches: 2
  
model:
  crop_size: [128, 96, 128]
  patch_size: [96, 128, 128]
  batch_size: 4
  x_axis_flip: True
  return_type: 'iso'  # 'fdi' for 11-48, or 'iso' for 1-32
  roi:
    lr: 0.0001
    epochs: 60
    weight_decay: 0.01
    # pretrained: ''
    pretrained: 'checkpoints_toothfairy2/relunet_roi.ckpt'
    out_channels: 1
  multiclass:
    lr: 0.0001
    epochs: 70
    weight_decay: 0.01
    # pretrained: ''
    pretrained: 'checkpoints_toothfairy2/relunet_multiclass.ckpt'
    out_channels: 33
  single_tooth:
    lr: 0.0001
    epochs: 200
    weight_decay: 0.01
    pretrained: 'checkpoints_toothfairy2/relunet_single_tooth.ckpt'
    out_channels: 1
